"""
Legal access and court export models.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class LegalAccess(Base, UUIDMixin, TimestampMixin):
    """
    Professional access to case data (GAL, attorneys, mediators, etc.).
    """

    __tablename__ = "legal_access"

    # Case link
    case_id: Mapped[str] = mapped_column(String(36), ForeignKey("cases.id"), index=True)

    # Professional information
    professional_email: Mapped[str] = mapped_column(String(255), index=True)
    professional_name: Mapped[str] = mapped_column(String(200))
    professional_phone: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)

    # Role
    role: Mapped[str] = mapped_column(
        String(50)
    )  # gal, attorney_petitioner, attorney_respondent, mediator, clerk, judge
    organization: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)

    # Credentials
    bar_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    license_state: Mapped[Optional[str]] = mapped_column(String(2), nullable=True)
    appointment_letter_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Access scope
    access_scope: Mapped[list] = mapped_column(JSON)  # List of modules they can access
    # e.g., ["schedule", "messages", "financials", "agreements"]

    # Time restrictions
    start_date: Mapped[datetime] = mapped_column(DateTime)
    end_date: Mapped[datetime] = mapped_column(DateTime)
    default_duration_days: Mapped[int] = mapped_column(Integer)  # Based on role

    # Status
    status: Mapped[str] = mapped_column(
        String(20), default="pending"
    )  # pending, verified, active, expired, revoked
    is_active: Mapped[bool] = mapped_column(Boolean, default=False)

    # Verification
    verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    verified_by: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)  # User ID
    verification_method: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    # joint_consent, court_order, bar_verification

    # MFA requirement
    mfa_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    mfa_verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Approval
    approved_by_petitioner: Mapped[bool] = mapped_column(Boolean, default=False)
    approved_by_respondent: Mapped[bool] = mapped_column(Boolean, default=False)
    petitioner_approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    respondent_approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Access tracking
    last_access_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    access_count: Mapped[int] = mapped_column(Integer, default=0)

    # Termination
    revoked_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    revoked_by: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    revocation_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Notes
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<LegalAccess {self.role} for case {self.case_id}>"

    @property
    def is_expired(self) -> bool:
        """Check if access has expired."""
        return datetime.utcnow() > self.end_date

    @property
    def is_valid(self) -> bool:
        """Check if access is currently valid."""
        return (
            self.is_active
            and self.status == "active"
            and not self.is_expired
            and self.mfa_enabled
        )


class CourtExport(Base, UUIDMixin, TimestampMixin):
    """
    Court export package - generated reports for legal proceedings.
    """

    __tablename__ = "court_exports"

    # Case link
    case_id: Mapped[str] = mapped_column(String(36), ForeignKey("cases.id"), index=True)

    # Package info
    package_type: Mapped[str] = mapped_column(
        String(50)
    )  # investigation, court_package, compliance_summary
    package_number: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    # e.g., "PKT-20251226-4827"

    # Generated by
    generated_by: Mapped[str] = mapped_column(String(36))  # User ID or professional
    generated_for: Mapped[str] = mapped_column(String(200))  # Person/organization name

    # Date range
    data_start_date: Mapped[datetime] = mapped_column(DateTime)
    data_end_date: Mapped[datetime] = mapped_column(DateTime)

    # Sections included
    sections: Mapped[list] = mapped_column(JSON)
    # e.g., ["agreement", "compliance", "schedule", "financials", "messages", "interventions"]

    # File information
    pdf_url: Mapped[str] = mapped_column(String(500))
    pdf_size_bytes: Mapped[int] = mapped_column(Integer)
    page_count: Mapped[int] = mapped_column(Integer)

    # Integrity
    content_hash: Mapped[str] = mapped_column(String(64))  # SHA-256
    chain_of_custody_hash: Mapped[str] = mapped_column(String(64))
    integrity_verified: Mapped[bool] = mapped_column(Boolean, default=True)

    # Watermarking
    watermark_text: Mapped[str] = mapped_column(String(200))
    # e.g., "Generated for: Sarah Mitchell, GAL - 2025-12-26 14:32 UTC"

    # Verification URL
    verification_url: Mapped[str] = mapped_column(String(500))
    # e.g., "verify.commonground.family/PKT-20251226-4827"

    # Evidence summary
    evidence_count: Mapped[dict] = mapped_column(JSON)
    # e.g., {"messages": 156, "exchanges": 24, "payments": 12}

    # Status
    status: Mapped[str] = mapped_column(String(20), default="generated")  # generated, downloaded, submitted
    downloaded_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    download_count: Mapped[int] = mapped_column(Integer, default=0)

    # Expiration
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime, nullable=True
    )  # For temporary packages
    is_permanent: Mapped[bool] = mapped_column(Boolean, default=True)

    # Notes
    generation_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    purpose: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<CourtExport {self.package_number}>"

    @property
    def is_expired(self) -> bool:
        """Check if package has expired."""
        if self.is_permanent:
            return False
        return self.expires_at and datetime.utcnow() > self.expires_at
