"""add_pickup_dropoff_child_ids_to_custody_exchanges

Revision ID: 058211ae8004
Revises: ed2ad59f5f2d
Create Date: 2026-01-05 11:23:20.094242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058211ae8004'
down_revision: Union[str, Sequence[str], None] = 'ed2ad59f5f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable with server default for existing rows
    op.add_column('custody_exchanges', sa.Column('pickup_child_ids', sa.JSON(), nullable=True, server_default='[]'))
    op.add_column('custody_exchanges', sa.Column('dropoff_child_ids', sa.JSON(), nullable=True, server_default='[]'))

    # Update existing records to have empty arrays
    op.execute("UPDATE custody_exchanges SET pickup_child_ids = '[]' WHERE pickup_child_ids IS NULL")
    op.execute("UPDATE custody_exchanges SET dropoff_child_ids = '[]' WHERE dropoff_child_ids IS NULL")

    # Remove server defaults (no longer needed after population)
    op.alter_column('custody_exchanges', 'pickup_child_ids', server_default=None)
    op.alter_column('custody_exchanges', 'dropoff_child_ids', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custody_exchanges', 'dropoff_child_ids')
    op.drop_column('custody_exchanges', 'pickup_child_ids')
    # ### end Alembic commands ###
