"""add_court_event_rsvp_fields

Revision ID: 16fb0b9aaf32
Revises: 1c4aa74af40b
Create Date: 2026-01-02 17:17:53.816045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fb0b9aaf32'
down_revision: Union[str, Sequence[str], None] = '1c4aa74af40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_events', sa.Column('petitioner_rsvp_status', sa.String(length=20), nullable=True))
    op.add_column('court_events', sa.Column('respondent_rsvp_status', sa.String(length=20), nullable=True))
    op.add_column('court_events', sa.Column('petitioner_rsvp_at', sa.DateTime(), nullable=True))
    op.add_column('court_events', sa.Column('respondent_rsvp_at', sa.DateTime(), nullable=True))
    op.add_column('court_events', sa.Column('petitioner_rsvp_notes', sa.Text(), nullable=True))
    op.add_column('court_events', sa.Column('respondent_rsvp_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_events', 'respondent_rsvp_notes')
    op.drop_column('court_events', 'petitioner_rsvp_notes')
    op.drop_column('court_events', 'respondent_rsvp_at')
    op.drop_column('court_events', 'petitioner_rsvp_at')
    op.drop_column('court_events', 'respondent_rsvp_status')
    op.drop_column('court_events', 'petitioner_rsvp_status')
    # ### end Alembic commands ###
