"""add_family_file_id_to_custody_exchanges

Revision ID: 2b49574c7652
Revises: 2a2f1e6a170c
Create Date: 2026-01-04 22:55:27.608283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b49574c7652'
down_revision: Union[str, Sequence[str], None] = '2a2f1e6a170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custody_exchanges', sa.Column('family_file_id', sa.String(length=36), nullable=True))
    op.alter_column('custody_exchanges', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_custody_exchanges_family_file_id'), 'custody_exchanges', ['family_file_id'], unique=False)
    op.create_foreign_key(None, 'custody_exchanges', 'family_files', ['family_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custody_exchanges', type_='foreignkey')
    op.drop_index(op.f('ix_custody_exchanges_family_file_id'), table_name='custody_exchanges')
    op.alter_column('custody_exchanges', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('custody_exchanges', 'family_file_id')
    # ### end Alembic commands ###
