"""add edits_allowed fields to court_form_submissions

Revision ID: 5bdc949ee143
Revises: 16fb0b9aaf32
Create Date: 2026-01-03 15:24:13.581078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdc949ee143'
down_revision: Union[str, Sequence[str], None] = '16fb0b9aaf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add edits_allowed with default value of False for existing rows
    op.add_column('court_form_submissions', sa.Column('edits_allowed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('court_form_submissions', sa.Column('edits_allowed_by', sa.String(length=36), nullable=True))
    op.add_column('court_form_submissions', sa.Column('edits_allowed_at', sa.DateTime(), nullable=True))
    op.add_column('court_form_submissions', sa.Column('edits_allowed_notes', sa.Text(), nullable=True))
    op.add_column('court_form_submissions', sa.Column('edits_allowed_sections', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_form_submissions', 'edits_allowed_sections')
    op.drop_column('court_form_submissions', 'edits_allowed_notes')
    op.drop_column('court_form_submissions', 'edits_allowed_at')
    op.drop_column('court_form_submissions', 'edits_allowed_by')
    op.drop_column('court_form_submissions', 'edits_allowed')
    # ### end Alembic commands ###
