"""Add custody order models for FL-311 extraction

Revision ID: 63a2488603bd
Revises: 7e60b95aa043
Create Date: 2026-01-02 11:00:24.803594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a2488603bd'
down_revision: Union[str, Sequence[str], None] = '7e60b95aa043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
