"""add_agreement_id_to_messages_obligations_exchanges

Revision ID: 6640a6780278
Revises: b3c4d5e6f7g8
Create Date: 2026-01-04 13:15:50.207329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6640a6780278'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('court_custody_cases', 'case_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'custody'::character varying"))
    op.alter_column('court_custody_cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.add_column('custody_exchanges', sa.Column('agreement_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_custody_exchanges_agreement_id'), 'custody_exchanges', ['agreement_id'], unique=False)
    op.create_foreign_key(None, 'custody_exchanges', 'agreements', ['agreement_id'], ['id'])
    op.alter_column('family_files', 'parent_a_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'parent_a'::character varying"))
    op.alter_column('family_files', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('family_files', 'conflict_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('family_files', 'aria_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'claude'::character varying"))
    op.add_column('message_threads', sa.Column('agreement_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_message_threads_agreement_id'), 'message_threads', ['agreement_id'], unique=False)
    op.create_foreign_key(None, 'message_threads', 'agreements', ['agreement_id'], ['id'])
    op.add_column('messages', sa.Column('agreement_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_messages_agreement_id'), 'messages', ['agreement_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'agreements', ['agreement_id'], ['id'])
    op.add_column('obligations', sa.Column('agreement_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_obligations_agreement_id'), 'obligations', ['agreement_id'], unique=False)
    op.create_foreign_key(None, 'obligations', 'agreements', ['agreement_id'], ['id'])
    op.alter_column('quick_accords', 'child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('quick_accords', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('quick_accords', 'attestation_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'I attest this agreement reflects our mutual understanding for this specific situation.'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quick_accords', 'attestation_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'I attest this agreement reflects our mutual understanding for this specific situation.'::text"))
    op.alter_column('quick_accords', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('quick_accords', 'child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_index(op.f('ix_obligations_agreement_id'), table_name='obligations')
    op.drop_column('obligations', 'agreement_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_agreement_id'), table_name='messages')
    op.drop_column('messages', 'agreement_id')
    op.drop_constraint(None, 'message_threads', type_='foreignkey')
    op.drop_index(op.f('ix_message_threads_agreement_id'), table_name='message_threads')
    op.drop_column('message_threads', 'agreement_id')
    op.alter_column('family_files', 'aria_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'claude'::character varying"))
    op.alter_column('family_files', 'conflict_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('family_files', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('family_files', 'parent_a_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'parent_a'::character varying"))
    op.drop_constraint(None, 'custody_exchanges', type_='foreignkey')
    op.drop_index(op.f('ix_custody_exchanges_agreement_id'), table_name='custody_exchanges')
    op.drop_column('custody_exchanges', 'agreement_id')
    op.alter_column('court_custody_cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('court_custody_cases', 'case_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'custody'::character varying"))
    # ### end Alembic commands ###
