"""Add My Time Collections, Time Blocks, and Event Attendance for Schedule MVP

Revision ID: 6d4f495cd7b4
Revises: b2a417ae2714
Create Date: 2025-12-31 13:35:07.207789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4f495cd7b4'
down_revision: Union[str, Sequence[str], None] = 'b2a417ae2714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create my_time_collections table
    op.create_table(
        'my_time_collections',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('case_id', sa.String(length=36), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False, server_default='#3B82F6'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_my_time_collections_case_id', 'my_time_collections', ['case_id'], unique=False)
    op.create_index('ix_my_time_collections_owner_id', 'my_time_collections', ['owner_id'], unique=False)

    # 2. Create time_blocks table
    op.create_table(
        'time_blocks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('collection_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('all_day', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('recurrence_pattern', sa.String(length=20), nullable=True),
        sa.Column('recurrence_days', sa.JSON(), nullable=True),
        sa.Column('recurrence_end_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['collection_id'], ['my_time_collections.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_blocks_collection_id', 'time_blocks', ['collection_id'], unique=False)
    op.create_index('ix_time_blocks_start_time', 'time_blocks', ['start_time'], unique=False)
    op.create_index('ix_time_blocks_end_time', 'time_blocks', ['end_time'], unique=False)

    # 3. Create event_attendance table
    op.create_table(
        'event_attendance',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('parent_id', sa.String(length=36), nullable=False),
        sa.Column('invited_role', sa.String(length=20), nullable=False, server_default='optional'),
        sa.Column('invited_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('rsvp_status', sa.String(length=20), nullable=False, server_default='no_response'),
        sa.Column('rsvp_at', sa.DateTime(), nullable=True),
        sa.Column('rsvp_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['event_id'], ['schedule_events.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id', 'parent_id', name='uq_event_attendance_parent')
    )
    op.create_index('ix_event_attendance_event_id', 'event_attendance', ['event_id'], unique=False)
    op.create_index('ix_event_attendance_parent_id', 'event_attendance', ['parent_id'], unique=False)

    # 4. Update schedule_events table
    op.add_column('schedule_events', sa.Column('collection_id', sa.String(length=36), nullable=True))
    op.add_column('schedule_events', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('schedule_events', sa.Column('visibility', sa.String(length=20), nullable=False, server_default='co_parent'))
    op.add_column('schedule_events', sa.Column('location_shared', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_schedule_events_collection_id'), 'schedule_events', ['collection_id'], unique=False)
    op.create_index(op.f('ix_schedule_events_created_by'), 'schedule_events', ['created_by'], unique=False)
    op.create_foreign_key(None, 'schedule_events', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'schedule_events', 'my_time_collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop schedule_events updates
    op.drop_constraint(None, 'schedule_events', type_='foreignkey')
    op.drop_constraint(None, 'schedule_events', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_events_created_by'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_collection_id'), table_name='schedule_events')
    op.drop_column('schedule_events', 'location_shared')
    op.drop_column('schedule_events', 'visibility')
    op.drop_column('schedule_events', 'created_by')
    op.drop_column('schedule_events', 'collection_id')

    # 2. Drop event_attendance table
    op.drop_index('ix_event_attendance_parent_id', table_name='event_attendance')
    op.drop_index('ix_event_attendance_event_id', table_name='event_attendance')
    op.drop_table('event_attendance')

    # 3. Drop time_blocks table
    op.drop_index('ix_time_blocks_end_time', table_name='time_blocks')
    op.drop_index('ix_time_blocks_start_time', table_name='time_blocks')
    op.drop_index('ix_time_blocks_collection_id', table_name='time_blocks')
    op.drop_table('time_blocks')

    # 4. Drop my_time_collections table
    op.drop_index('ix_my_time_collections_owner_id', table_name='my_time_collections')
    op.drop_index('ix_my_time_collections_case_id', table_name='my_time_collections')
    op.drop_table('my_time_collections')

    # ### end Alembic commands ###
