"""Initial schema

Revision ID: 6d8cf63e69bd
Revises: 
Create Date: 2025-12-30 00:05:47.652070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8cf63e69bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('case_name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('court', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('separation_date', sa.DateTime(), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('judgment_date', sa.DateTime(), nullable=True),
    sa.Column('require_joint_approval', sa.Boolean(), nullable=False),
    sa.Column('allow_modifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('notification_sms', sa.Boolean(), nullable=False),
    sa.Column('notification_push', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('supabase_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('agreements',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('agreement_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('petitioner_approved', sa.Boolean(), nullable=False),
    sa.Column('petitioner_approved_at', sa.DateTime(), nullable=True),
    sa.Column('respondent_approved', sa.Boolean(), nullable=False),
    sa.Column('respondent_approved_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('court_ordered', sa.Boolean(), nullable=False),
    sa.Column('court_order_number', sa.String(length=100), nullable=True),
    sa.Column('court_order_date', sa.DateTime(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_case_id'), 'agreements', ['case_id'], unique=False)
    op.create_table('case_participants',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('parent_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('can_view_financials', sa.Boolean(), nullable=False),
    sa.Column('can_view_messages', sa.Boolean(), nullable=False),
    sa.Column('can_modify_agreement', sa.Boolean(), nullable=False),
    sa.Column('can_invite_legal_access', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_user_id'), 'case_participants', ['user_id'], unique=False)
    op.create_table('children',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=True),
    sa.Column('birth_state', sa.String(length=2), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('has_special_needs', sa.Boolean(), nullable=False),
    sa.Column('special_needs_notes', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('pediatrician_name', sa.String(length=200), nullable=True),
    sa.Column('pediatrician_phone', sa.String(length=20), nullable=True),
    sa.Column('insurance_provider', sa.String(length=200), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('teacher_name', sa.String(length=200), nullable=True),
    sa.Column('has_iep', sa.Boolean(), nullable=False),
    sa.Column('has_504', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_case_id'), 'children', ['case_id'], unique=False)
    op.create_table('court_exports',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('package_number', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('generated_for', sa.String(length=200), nullable=False),
    sa.Column('data_start_date', sa.DateTime(), nullable=False),
    sa.Column('data_end_date', sa.DateTime(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_of_custody_hash', sa.String(length=64), nullable=False),
    sa.Column('integrity_verified', sa.Boolean(), nullable=False),
    sa.Column('watermark_text', sa.String(length=200), nullable=False),
    sa.Column('verification_url', sa.String(length=500), nullable=False),
    sa.Column('evidence_count', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('generation_notes', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_exports_case_id'), 'court_exports', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_exports_package_number'), 'court_exports', ['package_number'], unique=True)
    op.create_table('event_logs',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('related_user_id', sa.String(length=36), nullable=True),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.Column('related_resource_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_case_id'), 'event_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_event_logs_content_hash'), 'event_logs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_sequence_number'), 'event_logs', ['sequence_number'], unique=False)
    op.create_table('expense_requests',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('requested_from', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requesting_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('split_percentage', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('child_ids', sa.JSON(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_fully_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('agreement_id', sa.String(length=36), nullable=True),
    sa.Column('agreement_section', sa.String(length=50), nullable=True),
    sa.Column('response_time_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_requests_case_id'), 'expense_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_requested_by'), 'expense_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_expense_requests_requested_from'), 'expense_requests', ['requested_from'], unique=False)
    op.create_table('legal_access',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('professional_email', sa.String(length=255), nullable=False),
    sa.Column('professional_name', sa.String(length=200), nullable=False),
    sa.Column('professional_phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('bar_number', sa.String(length=50), nullable=True),
    sa.Column('license_state', sa.String(length=2), nullable=True),
    sa.Column('appointment_letter_url', sa.String(length=500), nullable=True),
    sa.Column('access_scope', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('default_duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_petitioner', sa.Boolean(), nullable=False),
    sa.Column('approved_by_respondent', sa.Boolean(), nullable=False),
    sa.Column('petitioner_approved_at', sa.DateTime(), nullable=True),
    sa.Column('respondent_approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_access_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_access_case_id'), 'legal_access', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_access_professional_email'), 'legal_access', ['professional_email'], unique=False)
    op.create_table('message_threads',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('thread_type', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_threads_case_id'), 'message_threads', ['case_id'], unique=False)
    op.create_table('payment_ledger',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('obligor_id', sa.String(length=36), nullable=False),
    sa.Column('obligee_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('expense_request_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_ledger_case_id'), 'payment_ledger', ['case_id'], unique=False)
    op.create_index(op.f('ix_payment_ledger_obligee_id'), 'payment_ledger', ['obligee_id'], unique=False)
    op.create_index(op.f('ix_payment_ledger_obligor_id'), 'payment_ledger', ['obligor_id'], unique=False)
    op.create_table('schedule_events',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('custodial_parent_id', sa.String(length=36), nullable=False),
    sa.Column('transition_from_id', sa.String(length=36), nullable=True),
    sa.Column('transition_to_id', sa.String(length=36), nullable=True),
    sa.Column('child_ids', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('is_exchange', sa.Boolean(), nullable=False),
    sa.Column('exchange_location', sa.String(length=300), nullable=True),
    sa.Column('exchange_lat', sa.Float(), nullable=True),
    sa.Column('exchange_lng', sa.Float(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('agreement_id', sa.String(length=36), nullable=True),
    sa.Column('is_agreement_derived', sa.Boolean(), nullable=False),
    sa.Column('is_modification', sa.Boolean(), nullable=False),
    sa.Column('modification_approved', sa.Boolean(), nullable=False),
    sa.Column('modification_requested_by', sa.String(length=36), nullable=True),
    sa.Column('modification_approved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_events_case_id'), 'schedule_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_schedule_events_end_time'), 'schedule_events', ['end_time'], unique=False)
    op.create_index(op.f('ix_schedule_events_start_time'), 'schedule_events', ['start_time'], unique=False)
    op.create_table('agreement_sections',
    sa.Column('agreement_id', sa.String(length=36), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_sections_agreement_id'), 'agreement_sections', ['agreement_id'], unique=False)
    op.create_table('agreement_versions',
    sa.Column('agreement_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('petitioner_approved', sa.Boolean(), nullable=False),
    sa.Column('petitioner_approved_at', sa.DateTime(), nullable=True),
    sa.Column('respondent_approved', sa.Boolean(), nullable=False),
    sa.Column('respondent_approved_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_versions_agreement_id'), 'agreement_versions', ['agreement_id'], unique=False)
    op.create_table('exchange_check_ins',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_role', sa.String(length=20), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('check_in_method', sa.String(length=20), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('minutes_early_late', sa.Integer(), nullable=False),
    sa.Column('is_on_time', sa.Boolean(), nullable=False),
    sa.Column('is_within_grace', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issues_reported', sa.Text(), nullable=True),
    sa.Column('children_present', sa.JSON(), nullable=False),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('verified_by_other_parent', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_check_ins_event_id'), 'exchange_check_ins', ['event_id'], unique=False)
    op.create_index(op.f('ix_exchange_check_ins_user_id'), 'exchange_check_ins', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_hidden_by_sender', sa.Boolean(), nullable=False),
    sa.Column('is_hidden_by_recipient', sa.Boolean(), nullable=False),
    sa.Column('is_starred_by_sender', sa.Boolean(), nullable=False),
    sa.Column('is_starred_by_recipient', sa.Boolean(), nullable=False),
    sa.Column('was_flagged', sa.Boolean(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('payments',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_request_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('receipt_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('payer_notes', sa.Text(), nullable=True),
    sa.Column('payee_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['expense_request_id'], ['expense_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_case_id'), 'payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_payments_expense_request_id'), 'payments', ['expense_request_id'], unique=False)
    op.create_index(op.f('ix_payments_payee_id'), 'payments', ['payee_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_table('message_flags',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('original_content_hash', sa.String(length=64), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=True),
    sa.Column('suggested_content_hash', sa.String(length=64), nullable=True),
    sa.Column('user_action', sa.String(length=20), nullable=False),
    sa.Column('user_action_at', sa.DateTime(), nullable=False),
    sa.Column('final_content_hash', sa.String(length=64), nullable=False),
    sa.Column('intervention_level', sa.Integer(), nullable=False),
    sa.Column('intervention_message', sa.Text(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_flags_message_id'), 'message_flags', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_flags_message_id'), table_name='message_flags')
    op.drop_table('message_flags')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payee_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_expense_request_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_case_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_exchange_check_ins_user_id'), table_name='exchange_check_ins')
    op.drop_index(op.f('ix_exchange_check_ins_event_id'), table_name='exchange_check_ins')
    op.drop_table('exchange_check_ins')
    op.drop_index(op.f('ix_agreement_versions_agreement_id'), table_name='agreement_versions')
    op.drop_table('agreement_versions')
    op.drop_index(op.f('ix_agreement_sections_agreement_id'), table_name='agreement_sections')
    op.drop_table('agreement_sections')
    op.drop_index(op.f('ix_schedule_events_start_time'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_end_time'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_case_id'), table_name='schedule_events')
    op.drop_table('schedule_events')
    op.drop_index(op.f('ix_payment_ledger_obligor_id'), table_name='payment_ledger')
    op.drop_index(op.f('ix_payment_ledger_obligee_id'), table_name='payment_ledger')
    op.drop_index(op.f('ix_payment_ledger_case_id'), table_name='payment_ledger')
    op.drop_table('payment_ledger')
    op.drop_index(op.f('ix_message_threads_case_id'), table_name='message_threads')
    op.drop_table('message_threads')
    op.drop_index(op.f('ix_legal_access_professional_email'), table_name='legal_access')
    op.drop_index(op.f('ix_legal_access_case_id'), table_name='legal_access')
    op.drop_table('legal_access')
    op.drop_index(op.f('ix_expense_requests_requested_from'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_requested_by'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_case_id'), table_name='expense_requests')
    op.drop_table('expense_requests')
    op.drop_index(op.f('ix_event_logs_sequence_number'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_content_hash'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_case_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_court_exports_package_number'), table_name='court_exports')
    op.drop_index(op.f('ix_court_exports_case_id'), table_name='court_exports')
    op.drop_table('court_exports')
    op.drop_index(op.f('ix_children_case_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_case_participants_user_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_table('case_participants')
    op.drop_index(op.f('ix_agreements_case_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
