"""add court access mode tables

Revision ID: 8329cf5409d0
Revises: a484804e0d92
Create Date: 2025-12-31 18:52:21.511882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8329cf5409d0'
down_revision: Union[str, Sequence[str], None] = 'a484804e0d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_professionals',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=100), nullable=True),
    sa.Column('mfa_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_professionals_email'), 'court_professionals', ['email'], unique=True)
    op.create_table('court_access_grants',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('access_scope', sa.JSON(), nullable=False),
    sa.Column('data_start_date', sa.Date(), nullable=True),
    sa.Column('data_end_date', sa.Date(), nullable=True),
    sa.Column('authorization_type', sa.String(length=50), nullable=False),
    sa.Column('authorization_reference', sa.String(length=100), nullable=True),
    sa.Column('authorized_by', sa.JSON(), nullable=True),
    sa.Column('petitioner_approved', sa.Boolean(), nullable=False),
    sa.Column('respondent_approved', sa.Boolean(), nullable=False),
    sa.Column('petitioner_approved_at', sa.DateTime(), nullable=True),
    sa.Column('respondent_approved_at', sa.DateTime(), nullable=True),
    sa.Column('access_code', sa.String(length=64), nullable=True),
    sa.Column('access_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('sealed_items_access', sa.Boolean(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['court_professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_access_grants_case_id'), 'court_access_grants', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_access_grants_professional_id'), 'court_access_grants', ['professional_id'], unique=False)
    op.create_table('court_case_settings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('gps_checkins_required', sa.Boolean(), nullable=False),
    sa.Column('supervised_exchange_required', sa.Boolean(), nullable=False),
    sa.Column('aria_enforcement_locked', sa.Boolean(), nullable=False),
    sa.Column('in_app_communication_only', sa.Boolean(), nullable=False),
    sa.Column('agreement_edits_locked', sa.Boolean(), nullable=False),
    sa.Column('investigation_mode', sa.Boolean(), nullable=False),
    sa.Column('child_safety_tracking', sa.Boolean(), nullable=False),
    sa.Column('financial_verification_required', sa.Boolean(), nullable=False),
    sa.Column('set_by_professional_id', sa.String(length=36), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=True),
    sa.Column('court_order_reference', sa.String(length=100), nullable=True),
    sa.Column('settings_history', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_case_settings_case_id'), 'court_case_settings', ['case_id'], unique=True)
    op.create_table('court_events',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('petitioner_required', sa.Boolean(), nullable=False),
    sa.Column('respondent_required', sa.Boolean(), nullable=False),
    sa.Column('petitioner_attended', sa.Boolean(), nullable=True),
    sa.Column('respondent_attended', sa.Boolean(), nullable=True),
    sa.Column('petitioner_attendance_notes', sa.Text(), nullable=True),
    sa.Column('respondent_attendance_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('shared_notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_events_case_id'), 'court_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_events_created_by'), 'court_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_court_events_event_date'), 'court_events', ['event_date'], unique=False)
    op.create_table('court_messages',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sent_by', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('to_petitioner', sa.Boolean(), nullable=False),
    sa.Column('to_respondent', sa.Boolean(), nullable=False),
    sa.Column('petitioner_read_at', sa.DateTime(), nullable=True),
    sa.Column('respondent_read_at', sa.DateTime(), nullable=True),
    sa.Column('replies_allowed', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_messages_case_id'), 'court_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_messages_sent_by'), 'court_messages', ['sent_by'], unique=False)
    op.create_table('investigation_reports',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('sections_included', sa.JSON(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_of_custody_hash', sa.String(length=64), nullable=True),
    sa.Column('watermark_text', sa.String(length=200), nullable=False),
    sa.Column('verification_url', sa.String(length=500), nullable=False),
    sa.Column('evidence_counts', sa.JSON(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_reports_case_id'), 'investigation_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_reports_generated_by'), 'investigation_reports', ['generated_by'], unique=False)
    op.create_index(op.f('ix_investigation_reports_report_number'), 'investigation_reports', ['report_number'], unique=True)
    op.create_table('court_access_logs',
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['court_access_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_access_logs_case_id'), 'court_access_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_access_logs_grant_id'), 'court_access_logs', ['grant_id'], unique=False)
    op.create_index(op.f('ix_court_access_logs_professional_id'), 'court_access_logs', ['professional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_court_access_logs_professional_id'), table_name='court_access_logs')
    op.drop_index(op.f('ix_court_access_logs_grant_id'), table_name='court_access_logs')
    op.drop_index(op.f('ix_court_access_logs_case_id'), table_name='court_access_logs')
    op.drop_table('court_access_logs')
    op.drop_index(op.f('ix_investigation_reports_report_number'), table_name='investigation_reports')
    op.drop_index(op.f('ix_investigation_reports_generated_by'), table_name='investigation_reports')
    op.drop_index(op.f('ix_investigation_reports_case_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    op.drop_index(op.f('ix_court_messages_sent_by'), table_name='court_messages')
    op.drop_index(op.f('ix_court_messages_case_id'), table_name='court_messages')
    op.drop_table('court_messages')
    op.drop_index(op.f('ix_court_events_event_date'), table_name='court_events')
    op.drop_index(op.f('ix_court_events_created_by'), table_name='court_events')
    op.drop_index(op.f('ix_court_events_case_id'), table_name='court_events')
    op.drop_table('court_events')
    op.drop_index(op.f('ix_court_case_settings_case_id'), table_name='court_case_settings')
    op.drop_table('court_case_settings')
    op.drop_index(op.f('ix_court_access_grants_professional_id'), table_name='court_access_grants')
    op.drop_index(op.f('ix_court_access_grants_case_id'), table_name='court_access_grants')
    op.drop_table('court_access_grants')
    op.drop_index(op.f('ix_court_professionals_email'), table_name='court_professionals')
    op.drop_table('court_professionals')
    # ### end Alembic commands ###
