"""add_event_category_and_category_data

Revision ID: 93bc0e0fa9b0
Revises: 6d4f495cd7b4
Create Date: 2025-12-31 16:12:14.671478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bc0e0fa9b0'
down_revision: Union[str, Sequence[str], None] = '6d4f495cd7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add event_category with default value for existing records
    op.add_column('schedule_events', sa.Column('event_category', sa.String(length=50), nullable=False, server_default='general'))
    op.add_column('schedule_events', sa.Column('category_data', sa.JSON(), nullable=True))
    op.alter_column('schedule_events', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'co_parent'::character varying"))
    op.alter_column('schedule_events', 'location_shared',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_events', 'location_shared',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('schedule_events', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'co_parent'::character varying"))
    op.drop_column('schedule_events', 'category_data')
    op.drop_column('schedule_events', 'event_category')
    # ### end Alembic commands ###
