"""add_family_file_id_to_payment_ledger

Revision ID: a45949d45c55
Revises: 2b49574c7652
Create Date: 2026-01-04 23:55:31.124345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45949d45c55'
down_revision: Union[str, Sequence[str], None] = '2b49574c7652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_ledger', sa.Column('family_file_id', sa.String(length=36), nullable=True))
    op.alter_column('payment_ledger', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_payment_ledger_family_file_id'), 'payment_ledger', ['family_file_id'], unique=False)
    op.create_foreign_key(None, 'payment_ledger', 'family_files', ['family_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_payment_ledger_family_file_id'), table_name='payment_ledger')
    op.alter_column('payment_ledger', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('payment_ledger', 'family_file_id')
    # ### end Alembic commands ###
