"""add_custody_exchange_tables

Revision ID: a484804e0d92
Revises: 93bc0e0fa9b0
Create Date: 2025-12-31 17:09:14.219725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a484804e0d92'
down_revision: Union[str, Sequence[str], None] = '93bc0e0fa9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_exchanges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('exchange_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('from_parent_id', sa.String(length=36), nullable=True),
    sa.Column('to_parent_id', sa.String(length=36), nullable=True),
    sa.Column('child_ids', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_days', sa.JSON(), nullable=True),
    sa.Column('recurrence_end_date', sa.DateTime(), nullable=True),
    sa.Column('recurrence_exceptions', sa.JSON(), nullable=True),
    sa.Column('items_to_bring', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes_visible_to_coparent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_exchanges_case_id'), 'custody_exchanges', ['case_id'], unique=False)
    op.create_table('custody_exchange_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exchange_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('from_parent_checked_in', sa.Boolean(), nullable=False),
    sa.Column('from_parent_check_in_time', sa.DateTime(), nullable=True),
    sa.Column('to_parent_checked_in', sa.Boolean(), nullable=False),
    sa.Column('to_parent_check_in_time', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('override_location', sa.String(length=500), nullable=True),
    sa.Column('override_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['custody_exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_exchange_instances_exchange_id'), 'custody_exchange_instances', ['exchange_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custody_exchange_instances_exchange_id'), table_name='custody_exchange_instances')
    op.drop_table('custody_exchange_instances')
    op.drop_index(op.f('ix_custody_exchanges_case_id'), table_name='custody_exchanges')
    op.drop_table('custody_exchanges')
    # ### end Alembic commands ###
