"""add_aria_settings_to_cases

Revision ID: b2a417ae2714
Revises: 7267d0385948
Create Date: 2025-12-31 12:11:12.899607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a417ae2714'
down_revision: Union[str, Sequence[str], None] = '7267d0385948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add ARIA settings columns with default values for existing rows
    op.add_column('cases', sa.Column('aria_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cases', sa.Column('aria_provider', sa.String(length=20), nullable=False, server_default='claude'))
    op.add_column('cases', sa.Column('aria_disabled_at', sa.DateTime(), nullable=True))
    op.add_column('cases', sa.Column('aria_disabled_by', sa.String(length=36), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'aria_disabled_by')
    op.drop_column('cases', 'aria_disabled_at')
    op.drop_column('cases', 'aria_provider')
    op.drop_column('cases', 'aria_enabled')
    # ### end Alembic commands ###
