"""Add foreign key and name fields to User model

Revision ID: e04a89b5d357
Revises: 6d8cf63e69bd
Create Date: 2025-12-30 00:34:47.052329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04a89b5d357'
down_revision: Union[str, Sequence[str], None] = '6d8cf63e69bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    # ### end Alembic commands ###
