"""add_family_file_id_to_cubbie_items

Revision ID: ed2ad59f5f2d
Revises: a45949d45c55
Create Date: 2026-01-05 11:00:33.948369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2ad59f5f2d'
down_revision: Union[str, Sequence[str], None] = 'a45949d45c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cubbie_items', sa.Column('family_file_id', sa.String(length=36), nullable=True))
    op.alter_column('cubbie_items', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_cubbie_items_family_file_id'), 'cubbie_items', ['family_file_id'], unique=False)
    op.create_foreign_key(None, 'cubbie_items', 'family_files', ['family_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cubbie_items', type_='foreignkey')
    op.drop_index(op.f('ix_cubbie_items_family_file_id'), table_name='cubbie_items')
    op.alter_column('cubbie_items', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('cubbie_items', 'family_file_id')
    # ### end Alembic commands ###
